# Translations template for nova_powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 2.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 03:14-0400\n"
"PO-Revision-Date: 2016-04-14 03:14-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: nova_powervm/virt/powervm/driver.py:612
#: nova_powervm/virt/powervm/driver.py:622
msgid "VM was not found during destroy operation."
msgstr "Во время операции уничтожения не найдена ВМ."

#: nova_powervm/virt/powervm/driver.py:1006
msgid "VM was not found during unplug operation as it is already possibly deleted"
msgstr "Виртуальная машина не найдена в ходе операции отключения. Вероятно, она уже удалена"

#: nova_powervm/virt/powervm/driver.py:1033
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: "
"%(ifaces)s"
msgstr ""
"Адрес my_ip (%(my_ip)s) не найден ни на одном из интерфейсов: "
"%(ifaces)s"

#: nova_powervm/virt/powervm/driver.py:1511
msgid "Rolling back live migration."
msgstr "Откат оперативной миграции."

#: nova_powervm/virt/powervm/driver.py:1923
#, python-format
msgid "Unable to parse event URI: %s from PowerVM."
msgstr "Ошибка анализа URI события: %s из PowerVM."

#: nova_powervm/virt/powervm/host.py:171
msgid ""
"Host CPU Metrics determined that the total cycles reported was less than "
"the used cycles.  This indicates an issue with the PCM data.  Please "
"investigate the results."
msgstr ""
"В соответствии с показателями CPU хоста общее число циклов в отчете меньше числа "
"использованных циклов. Возможно, возникла неполадка, связанная с данными PCM. "
"Изучите результаты."

#: nova_powervm/virt/powervm/media.py:310
#, python-format
msgid "Unable to read volume groups for Virtual I/O Server %s"
msgstr "Не удалось прочесть группы томов для виртуального сервера ввода-вывода %s"

#: nova_powervm/virt/powervm/vif.py:184 nova_powervm/virt/powervm/vif.py:272
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  The VIF was"
" not found on the instance."
msgstr ""
"Не удалось отсоединить VIF с mac %(mac)s для экземпляра %(inst)s. VIF"
" не найден в экземпляре."

#: nova_powervm/virt/powervm/disk/driver.py:200
#, python-format
msgid ""
"Failed to map boot disk %(disk_name)s of instance %(instance_name)s to "
"the management partition from Virtual I/O Server %(vios_name)s: %(exc)s"
msgstr ""
"Не удалось подключить загрузочный диск %(disk_name)s экземпляра %(instance_name)s к "
"разделу управления из виртуального сервера ввода-вывода %(vios_name)s: %(exc)s"

#: nova_powervm/virt/powervm/nvram/manager.py:193
#, python-format
msgid "Unable to store the NVRAM for instance: %s"
msgstr "Не удалось сохранить NVRAM для экземпляра: %s"

#: nova_powervm/virt/powervm/nvram/swift.py:183
#, python-format
msgid "Could not remove temporary file: %s"
msgstr "Не удалось удалить временный файл: %s"

#: nova_powervm/virt/powervm/tasks/storage.py:57
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be disconnected"
msgstr "Планируется отключение тома %(vol)s для экземпляра %(inst)s"

#: nova_powervm/virt/powervm/tasks/storage.py:73
#, python-format
msgid ""
"Unable to disconnect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Не удалось отключить том для %(inst)s в процессе отката. Ошибка: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:102
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be re-connected"
msgstr "Планируется повторное подключение тома %(vol)s для экземпляра %(inst)s"

#: nova_powervm/virt/powervm/tasks/storage.py:119
#, python-format
msgid ""
"Unable to re-connect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Не удалось повторно подключить том для %(inst)s в процессе отката. Ошибка: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:163
#, python-format
msgid "Image for instance %s to be deleted"
msgstr "Планируется удаление образа для экземпляра %s"

#: nova_powervm/virt/powervm/tasks/storage.py:211
#, python-format
msgid "Disk image being disconnected from instance %s"
msgstr "Образ диска отключается от экземпляра %s"

#: nova_powervm/virt/powervm/tasks/storage.py:283
#, python-format
msgid ""
"Unmapping boot disk %(disk_name)s of instance %(instance_name)s from "
"management partition via Virtual I/O Server %(vios_name)s."
msgstr ""
"Удаление связи загрузочного диска %(disk_name)s экземпляра %(instance_name)s из "
"раздела управления через виртуальный сервер ввода-вывода %(vios_name)s."

#: nova_powervm/virt/powervm/tasks/storage.py:295
#, python-format
msgid "Removing disk %(disk_path)s from the management partition."
msgstr "Удаление %(disk_path)s диска из раздела управления."

#: nova_powervm/virt/powervm/tasks/storage.py:549
#, python-format
msgid "Disk not found: %(disk_name)s"
msgstr "Диск не найден: %(disk_name)s"

#: nova_powervm/virt/powervm/volume/npiv.py:455
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC "
"Fabric %(fabric)s."
msgstr ""
"Между виртуальными серверами ввода-вывода и фабрикой "
"FC %(fabric)s не найдены подключения к памяти."

#: nova_powervm/virt/powervm/volume/npiv.py:573
#, python-format
msgid ""
"No NPIV mappings exist for instance %(inst)s on fabric %(fabric)s.  May "
"not have connected to the fabric yet or fabric configuration was recently"
" modified."
msgstr ""
"Нет связей NPIV для экземпляра %(inst)s в фабрике %(fabric)s. Возможно, "
"фабрика еще не подключена, или ее конфигурация недавно"
" изменялась."

#: nova_powervm/virt/powervm/volume/vscsi.py:127
#, python-format
msgid "Could not remove hdisk for volume: %s"
msgstr "Не удалось удалить жесткий диск для тома %s"

#: nova_powervm/virt/powervm/volume/vscsi.py:206
#, python-format
msgid ""
"Discovered device %(dev)s for volume %(volume)s on %(vios)s is in use. "
"Error code: %(status)s."
msgstr ""
"Обнаруженное устройство %(dev)s для тома %(volume)s на сервере %(vios)s занято. "
"Код ошибки: %(status)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:324
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual "
"I/O Server %(vios)s is not in a valid state.  No disconnect actions to be"
" taken as volume is not healthy."
msgstr ""
"Отключение тома: базовый жесткий диск для тома %(volume_id)s в VIOS "
"%(vios)s находится в недопустимом состоянии. Операции отключения"
" выполнять нельзя, поскольку том неисправен."

#: nova_powervm/virt/powervm/volume/vscsi.py:336
#, python-format
msgid ""
"Disconnect Volume: No mapped device found on Virtual I/O Server %(vios)s "
"for volume %(volume_id)s.  Volume UDID: %(volume_uid)s"
msgstr ""
"Отключение тома: на виртуальном сервере ввода-вывода %(vios)s не найдены подключенные устройства "
"для тома %(volume_id)s. UDID тома: %(volume_uid)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:345
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server "
"%(vios_name)s for volume %(volume_id)s. Volume UDID: %(volume_uid)s.  "
"Error: %(error)s"
msgstr ""
"Отключение тома: не удалось найти диск на виртуальном сервере ввода-вывода "
"%(vios_name)s для тома %(volume_id)s. UDID тома: %(volume_uid)s.  "
"Ошибка: %(error)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:386
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the volume %(volume_id)s on ANY "
"of the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Отключение тома: не удалось отключить том %(volume_id)s ни на одном из "
"виртуальных серверов ввода-вывода для экземпляра %(inst)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:442
#, python-format
msgid ""
"There was an error removing the hdisk %(disk)s from the Virtual I/O "
"Server."
msgstr ""
"Возникла ошибка при удалении жесткого диска %(disk)s из VIOS "
"."


# ENGL1SH_VERS10N 51377_8 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 49
# T9N_SH1P_STR1NG PV131AAP001 3
