# Translations template for nova_powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 2.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 03:14-0400\n"
"PO-Revision-Date: 2016-04-14 03:14-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: nova_powervm/virt/powervm/driver.py:612
#: nova_powervm/virt/powervm/driver.py:622
msgid "VM was not found during destroy operation."
msgstr "A VM não foi localizada durante a operação de destruição."

#: nova_powervm/virt/powervm/driver.py:1006
msgid "VM was not found during unplug operation as it is already possibly deleted"
msgstr "A máquina virtual não foi localizada durante a operação de desconexão, uma vez que possivelmente ela já foi excluída"

#: nova_powervm/virt/powervm/driver.py:1033
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: "
"%(ifaces)s"
msgstr ""
"O endereço my_ip (%(my_ip)s) não foi localizado em qualquer uma das interfaces: "
"%(ifaces)s"

#: nova_powervm/virt/powervm/driver.py:1511
msgid "Rolling back live migration."
msgstr "Retrocedendo a migração em tempo real."

#: nova_powervm/virt/powervm/driver.py:1923
#, python-format
msgid "Unable to parse event URI: %s from PowerVM."
msgstr "Não é possível analisar o URI do evento: %s a partir do PowerVM."

#: nova_powervm/virt/powervm/host.py:171
msgid ""
"Host CPU Metrics determined that the total cycles reported was less than "
"the used cycles.  This indicates an issue with the PCM data.  Please "
"investigate the results."
msgstr ""
"As métricas da CPU do host determinaram que os ciclos totais relatados eram menores que "
"os ciclos usados. Isso indica um problema com os dados de PCM. "
"Investigue os resultados."

#: nova_powervm/virt/powervm/media.py:310
#, python-format
msgid "Unable to read volume groups for Virtual I/O Server %s"
msgstr "Não é possível ler os grupos de volume para o Virtual I/O Server %s"

#: nova_powervm/virt/powervm/vif.py:184 nova_powervm/virt/powervm/vif.py:272
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  The VIF was"
" not found on the instance."
msgstr ""
"Não é possível desconectar VIF com MAC %(mac)s para a instância %(inst)s. O VIF"
" não foi localizado na instância."

#: nova_powervm/virt/powervm/disk/driver.py:200
#, python-format
msgid ""
"Failed to map boot disk %(disk_name)s of instance %(instance_name)s to "
"the management partition from Virtual I/O Server %(vios_name)s: %(exc)s"
msgstr ""
"Falha ao mapear o disco de inicialização %(disk_name)s da instância %(instance_name)s para "
"a partição de gerenciamento do Virtual I/O Server %(vios_name)s:%(exc)s"

#: nova_powervm/virt/powervm/nvram/manager.py:193
#, python-format
msgid "Unable to store the NVRAM for instance: %s"
msgstr "Não é possível armazenar o NVRAM para a instância: %s"

#: nova_powervm/virt/powervm/nvram/swift.py:183
#, python-format
msgid "Could not remove temporary file: %s"
msgstr "Não foi possível remover o arquivo temporário: %s"

#: nova_powervm/virt/powervm/tasks/storage.py:57
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be disconnected"
msgstr "O volume %(vol)s para a instância %(inst)s a ser desconectado"

#: nova_powervm/virt/powervm/tasks/storage.py:73
#, python-format
msgid ""
"Unable to disconnect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Não é possível desconectar o volume para %(inst)s durante o retrocesso. O erro foi: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:102
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be re-connected"
msgstr "Volume %(vol)s para instância %(inst)s a ser conectado novamente"

#: nova_powervm/virt/powervm/tasks/storage.py:119
#, python-format
msgid ""
"Unable to re-connect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Não é possível reconectar o volume para %(inst)s durante o retrocesso. O erro foi: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:163
#, python-format
msgid "Image for instance %s to be deleted"
msgstr "Imagem para a instância %s a ser excluída"

#: nova_powervm/virt/powervm/tasks/storage.py:211
#, python-format
msgid "Disk image being disconnected from instance %s"
msgstr "A imagem do disco está sendo desconectada da instância %s"

#: nova_powervm/virt/powervm/tasks/storage.py:283
#, python-format
msgid ""
"Unmapping boot disk %(disk_name)s of instance %(instance_name)s from "
"management partition via Virtual I/O Server %(vios_name)s."
msgstr ""
"Removendo o mapeamento do disco de inicialização %(disk_name)s da instância %(instance_name)s da "
"partição de gerenciamento por meio do Virtual I/O Server %(vios_name)s."

#: nova_powervm/virt/powervm/tasks/storage.py:295
#, python-format
msgid "Removing disk %(disk_path)s from the management partition."
msgstr "Removendo o disco %(disk_path)s da partição de gerenciamento."

#: nova_powervm/virt/powervm/tasks/storage.py:549
#, python-format
msgid "Disk not found: %(disk_name)s"
msgstr "Disco não localizado: %(disk_name)s"

#: nova_powervm/virt/powervm/volume/npiv.py:455
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC "
"Fabric %(fabric)s."
msgstr ""
"Não há conexões de armazenamento localizadas entre os Virtual I/O Servers e o FC "
"Malha %(fabric)s."

#: nova_powervm/virt/powervm/volume/npiv.py:573
#, python-format
msgid ""
"No NPIV mappings exist for instance %(inst)s on fabric %(fabric)s.  May "
"not have connected to the fabric yet or fabric configuration was recently"
" modified."
msgstr ""
"Não existem mapeamentos de NPIV para a instância %(inst)s na malha %(fabric)s. Pode "
"não ter conectado à malha ainda ou a configuração da malha foi recentemente"
" modificada."

#: nova_powervm/virt/powervm/volume/vscsi.py:127
#, python-format
msgid "Could not remove hdisk for volume: %s"
msgstr "Não foi possível remover o hdisk para o volume: %s"

#: nova_powervm/virt/powervm/volume/vscsi.py:206
#, python-format
msgid ""
"Discovered device %(dev)s for volume %(volume)s on %(vios)s is in use. "
"Error code: %(status)s."
msgstr ""
"Dispositivo descoberto %(dev)s para o volume %(volume)s no %(vios)s está em uso. "
"Código de erro: %(status)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:324
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual "
"I/O Server %(vios)s is not in a valid state.  No disconnect actions to be"
" taken as volume is not healthy."
msgstr ""
"Desconectar volume: o hdisk de apoio para o volume %(volume_id)s no Virtual "
"I/O Server %(vios)s não está em um estado válido. Ações de desconexão não devem"
" ser executadas porque o volume não está em funcionamento."

#: nova_powervm/virt/powervm/volume/vscsi.py:336
#, python-format
msgid ""
"Disconnect Volume: No mapped device found on Virtual I/O Server %(vios)s "
"for volume %(volume_id)s.  Volume UDID: %(volume_uid)s"
msgstr ""
"Volume de desconexão: nenhum dispositivo mapeado localizado no Virtual I/O Server %(vios)s "
"para o volume %(volume_id)s. UDID do volume: %(volume_uid)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:345
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server "
"%(vios_name)s for volume %(volume_id)s. Volume UDID: %(volume_uid)s.  "
"Error: %(error)s"
msgstr ""
"Volume de desconexão: falha ao localizar o disco no Virtual I/O Server "
"%(vios_name)s para o volume %(volume_id)s. O UDID do volume:%(volume_uid)s.  "
"Erro: %(error)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:386
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the volume %(volume_id)s on ANY "
"of the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Volume de desconexão: falha ao desconectar o volume %(volume_id)s em QUALQUER "
"um dos Virtual I/O Servers para a instância %(inst)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:442
#, python-format
msgid ""
"There was an error removing the hdisk %(disk)s from the Virtual I/O "
"Server."
msgstr ""
"Houve um erro ao remover o hdisk %(disk)s do Virtual I/O "
"Server."


# ENGL1SH_VERS10N 51377_8 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 49
# T9N_SH1P_STR1NG PV131AAP001 3
