# Translations template for nova_powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 2.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 03:14-0400\n"
"PO-Revision-Date: 2016-04-14 03:14-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: nova_powervm/virt/powervm/driver.py:612
#: nova_powervm/virt/powervm/driver.py:622
msgid "VM was not found during destroy operation."
msgstr "Die VM wurde während des Löschvorgangs nicht gefunden."

#: nova_powervm/virt/powervm/driver.py:1006
msgid "VM was not found during unplug operation as it is already possibly deleted"
msgstr "Die VM wurde während des Trennvorgangs nicht gefunden, da sie möglicherweise bereits gelöscht ist."

#: nova_powervm/virt/powervm/driver.py:1033
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: "
"%(ifaces)s"
msgstr ""
"Die my_ip Adresse (%(my_ip)s) wurde auf keiner der folgenden Schnittstellen gefunden: "
"%(ifaces)s"

#: nova_powervm/virt/powervm/driver.py:1511
msgid "Rolling back live migration."
msgstr "Ein Rollback der Livemigration wird durchgeführt."

#: nova_powervm/virt/powervm/driver.py:1923
#, python-format
msgid "Unable to parse event URI: %s from PowerVM."
msgstr "Ereignis-URI kann nicht ausgewertet werden: %s von PowerVM."

#: nova_powervm/virt/powervm/host.py:171
msgid ""
"Host CPU Metrics determined that the total cycles reported was less than "
"the used cycles.  This indicates an issue with the PCM data.  Please "
"investigate the results."
msgstr ""
"Anhand der Host-CPU-Metriken wurde festgestellt, dass die gemeldete Gesamtzahl Zyklen kleiner als "
"die Anzahl der verwendeten Zyklen war. Dies weist auf ein Problem mit den PCM-Daten hin. "
"Die Ergebnisse sollten überprüft werden."

#: nova_powervm/virt/powervm/media.py:310
#, python-format
msgid "Unable to read volume groups for Virtual I/O Server %s"
msgstr "Die Datenträgergruppen für den virtuellen E/A-Server %s konnten nicht gelesen werden."

#: nova_powervm/virt/powervm/vif.py:184 nova_powervm/virt/powervm/vif.py:272
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  The VIF was"
" not found on the instance."
msgstr ""
"Der VIF mit MAC %(mac)s für Instanz %(inst)s konnte nicht getrennt werden. Der VIF wurde"
" nicht auf der Instanz gefunden."

#: nova_powervm/virt/powervm/disk/driver.py:200
#, python-format
msgid ""
"Failed to map boot disk %(disk_name)s of instance %(instance_name)s to "
"the management partition from Virtual I/O Server %(vios_name)s: %(exc)s"
msgstr ""
"Fehler beim Zuordnen des Bootdatenträgers %(disk_name)s der Instanz %(instance_name)s zur "
"Managementpartition des virtuellen E/A-Servers %(vios_name)s: %(exc)s"

#: nova_powervm/virt/powervm/nvram/manager.py:193
#, python-format
msgid "Unable to store the NVRAM for instance: %s"
msgstr "Der nicht flüchtige Arbeitsspeicher für die Instanz: %s kann nicht gespeichert werden"

#: nova_powervm/virt/powervm/nvram/swift.py:183
#, python-format
msgid "Could not remove temporary file: %s"
msgstr "Die temporäre Datei: %s konnte nicht entfernt werden"

#: nova_powervm/virt/powervm/tasks/storage.py:57
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be disconnected"
msgstr "Zu trennender Datenträger %(vol)s für Instanz %(inst)s"

#: nova_powervm/virt/powervm/tasks/storage.py:73
#, python-format
msgid ""
"Unable to disconnect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Der Datenträger %(inst)s konnte während des Rollbacks nicht getrennt werden. Folgender Fehler wurde gemeldet: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:102
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be re-connected"
msgstr "Datenträger %(vol)s für Instanz %(inst)s, zu dem die Verbindung wiederhergestellt werden soll"

#: nova_powervm/virt/powervm/tasks/storage.py:119
#, python-format
msgid ""
"Unable to re-connect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Die Verbindung zum Datenträger %(inst)s konnte während des Rollbacks nicht wiederhergestellt werden. Folgender Fehler wurde gemeldet: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:163
#, python-format
msgid "Image for instance %s to be deleted"
msgstr "Zu löschendes Image für Instanz %s"

#: nova_powervm/virt/powervm/tasks/storage.py:211
#, python-format
msgid "Disk image being disconnected from instance %s"
msgstr "Plattenimage, das von der Instanz %s getrennt wird"

#: nova_powervm/virt/powervm/tasks/storage.py:283
#, python-format
msgid ""
"Unmapping boot disk %(disk_name)s of instance %(instance_name)s from "
"management partition via Virtual I/O Server %(vios_name)s."
msgstr ""
"Aufheben der Zuordnung der Bootplatte %(disk_name)s der Instanz %(instance_name)s von "
"Managementpartition wird über den virtuellen E/A-Server %(vios_name)s aufgehoben."

#: nova_powervm/virt/powervm/tasks/storage.py:295
#, python-format
msgid "Removing disk %(disk_path)s from the management partition."
msgstr "Die Platte %(disk_path)s wird von der Managementpartition entfernt."

#: nova_powervm/virt/powervm/tasks/storage.py:549
#, python-format
msgid "Disk not found: %(disk_name)s"
msgstr "Platte nicht gefunden: %(disk_name)s"

#: nova_powervm/virt/powervm/volume/npiv.py:455
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC "
"Fabric %(fabric)s."
msgstr ""
"Es wurden keine Speicherverbindungen gefunden zwischen den virtuellen E/A-Servern und FC "
"Fabric %(fabric)s."

#: nova_powervm/virt/powervm/volume/npiv.py:573
#, python-format
msgid ""
"No NPIV mappings exist for instance %(inst)s on fabric %(fabric)s.  May "
"not have connected to the fabric yet or fabric configuration was recently"
" modified."
msgstr ""
"Es sind keine NPIV-Zuordnungen für Instanz %(inst)s in Fabric %(fabric)s vorhanden. Möglicherweise "
"wurden sie noch nicht mit dem Fabric verbunden oder die Fabric-Konfiguration wurde vor kurzem"
" modifiziert."

#: nova_powervm/virt/powervm/volume/vscsi.py:127
#, python-format
msgid "Could not remove hdisk for volume: %s"
msgstr "Die HDisk für den Datenträger: %s konnte nicht entfernt werden"

#: nova_powervm/virt/powervm/volume/vscsi.py:206
#, python-format
msgid ""
"Discovered device %(dev)s for volume %(volume)s on %(vios)s is in use. "
"Error code: %(status)s."
msgstr ""
"Die erkannte Einheit %(dev)s für Datenträger %(volume)s auf %(vios)s wird bereits verwendet. "
"Fehlercode: %(status)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:324
#, python-format
msgid ""
"Disconnect Volume: The backing hdisk for volume %(volume_id)s on Virtual "
"I/O Server %(vios)s is not in a valid state.  No disconnect actions to be"
" taken as volume is not healthy."
msgstr ""
"Datenträger trennen: Die Sicherungs-HDisk für den Datenträger %(volume_id)s auf dem virtuellen "
"E/A-Server %(vios)s befindet sich in einem nicht gültigen Zustand. Es sind keine Aktionen zur Trennung der Verbindung"
" zu unternehmen, weil der Datenträger nicht in einwandfreiem Zustand ist."

#: nova_powervm/virt/powervm/volume/vscsi.py:336
#, python-format
msgid ""
"Disconnect Volume: No mapped device found on Virtual I/O Server %(vios)s "
"for volume %(volume_id)s.  Volume UDID: %(volume_uid)s"
msgstr ""
"Datenträger trennen: Auf dem virtuellen E/A-Server %(vios)s wurde keine zugeordnete Einheit "
"für den Datenträger %(volume_id)s gefunden. Datenträger-UDID: %(volume_uid)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:345
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server "
"%(vios_name)s for volume %(volume_id)s. Volume UDID: %(volume_uid)s.  "
"Error: %(error)s"
msgstr ""
"Datenträger trennen: Es wurde keine Platte auf dem virtuellen E/A-Server "
"%(vios_name)s für Datenträger %(volume_id)s gefunden. Datenträger-UDID: %(volume_uid)s.  "
"Fehler: %(error)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:386
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the volume %(volume_id)s on ANY "
"of the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Datenträger trennen: Die Trennung des Datenträgers %(volume_id)s ist auf ALLEN "
"virtuellen E/A-Servern für Instanz %(inst)s fehlgeschlagen."

#: nova_powervm/virt/powervm/volume/vscsi.py:442
#, python-format
msgid ""
"There was an error removing the hdisk %(disk)s from the Virtual I/O "
"Server."
msgstr ""
"Bei der Entfernung der HDisk %(disk)s vom virtuellen E/A-Server "
"ist ein Fehler aufgetreten."


# ENGL1SH_VERS10N 51377_8 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 49
# T9N_SH1P_STR1NG PV131AAP001 3
